[project]
name='flaskr'
version='1.0.0'
description='My flask app that I built using a flask tutiorial'
dependencies=[
    'flask',
]
[build-system]
requires=['flit_core<4']
build-backend='flit_core.buildapi'
